classdef TransferFunction
    properties
        Name
        Formel
    end
    methods
        function obj = TransferFunction(name,formel)
            obj.Name = string(name);
            obj.Formel = string(formel);
        end
        function G = toTF(obj)
            s = tf('s');
            G = eval(obj.Formel);
        end
        function z = zeros(obj)
            z = zero(obj.toTF());
        end
        function p = poles(obj)
            p = pole(obj.toTF());
        end
    end
    methods (Static)
        function list = makeTransferFunctions()
            list = [ ...
                TransferFunction("Aufgabe A","1/(s+1)"); ...
                TransferFunction("Aufgabe B","10/(s+10)"); ...
                TransferFunction("Aufgabe C","(s+1)/(s+10)"); ...
                TransferFunction("Aufgabe D","10*(1 - s)/(s+10)"); ...
                TransferFunction("Aufgabe E","(-1+1i)/(sqrt(2)*(s+1)^2)"); ...
                TransferFunction("Aufgabe F","-1000/((s+1)*(s+100))"); ...
                TransferFunction("Aufgabe G","(100*s)/(s+1)"); ...
                TransferFunction("Aufgabe H","(10*sqrt(2)*s^2)/(s-1)"); ...
                TransferFunction("Aufgabe I","(s+1)/(s+10)^2"); ...
                TransferFunction("Aufgabe J","(s+1)/(s^2 + 2*s + 1)"); ...
                TransferFunction("Aufgabe K","100*(s+1)/(s^2 + 20*s + 100)"); ...
                TransferFunction("Aufgabe L","(s^2 - 100)/(s+1)"); ...
                TransferFunction("Aufgabe M","(10*sqrt(202)*s)/((s+1)*(s+10))"); ...
                TransferFunction("Aufgabe N","s*(0.1 - s)*(s+10)/(s+1)^2"); ...
                TransferFunction("Aufgabe O","1/s"); ...
                TransferFunction("Aufgabe P","100/(s^2 + 1*s + 100)"); ...
                TransferFunction("Aufgabe Q","(s^2 + 4)/(s*(s^2 + 10*s + 100))"); ...
                TransferFunction("Aufgabe R","(s^2 + 2*s + 10)/(s^2 + 2*s + 10)"); ...
                TransferFunction("Aufgabe S","4/(s^2 - 4)"); ...
                TransferFunction("Aufgabe T","-1000*(s+2)^2/(4*(s+1)^3*(s+10))"); ...
                TransferFunction("Aufgabe U","2*s/(s^2 + 2*s + 1)") ...
            ];
            end
    end
end